on:
  workflow_call:

jobs:
  level-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Level 2
        run: echo "Level 2"

  level-2-external-call:
    needs: level-2
    uses: eamonnmoloney/github-env-bug-repo-2/.github/workflows/level-1.yaml@main
