on:
  workflow_call:
    inputs:
      test:
        description: 'Test'
        required: true
        type: string

jobs:
  level-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Level 2
        run: echo "${{ inputs.test }}"

  level-2-external-call:
    needs: level-2
    uses: eamonnmoloney/github-env-bug-repo-1/.github/workflows/level-1.yaml@main
